# Euclidean Cluster

bool switch_to  # 开关
bool ON = 1     # 启动
bool OFF = 0    # 关闭

float32 remove_points_upto
bool remove_ground
bool use_multiple_thres

bool downsample_cloud
float32 leaf_size

float32 clip_min_height
float32 clip_max_height

bool keep_lanes
float32 keep_lane_left_distance
float32 keep_lane_right_distance

int8 cluster_size_min
int8 cluster_size_max

float32 cluster_merge_threshold
float32 clustering_distance
